### ISSUE TITLE
Please do not include rant articles

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixos-weekly#89] opened 2019-03-13 18:58 UTC
Hi.

First of all: I really love the newsletter and it really helps to keep track of what is happening in the community!

That said, I'd like you to ask to not include articles like [Why you never should use NixOS](https://dev-ops-notes.com/nixos/why-you-should-never-ever-use-nixos/) in the newsletter. First of all, it is just pushing bullshit to visibility, but it is also not constructive and just wasting peoples times.

I have no problem with constructive criticism - I encourage it and we all should encourage it! But things like

> Do not listen anybody. Do not reinvent the wheel. Just waste it.

and

> Run away! Not, seriously! Run! From! It! Away!

or obviously false statements like

> It is not possible just to upgrade the kernel from “ver1” to “ver2”

 are not constructive and are a waste of time for everybody.

---

That said, thank you again for the newsletter and please keep up the good work!

**Comment by matthiasbeyer** [comment] 2019-03-13 19:01
From the nixos IRC channel:

> it wasn't so much that the author doesn't understand much about Nix, which is fine and can still be useful feedback, but rather that they seemed to assume that that MUST be a problem with Nix and it couldn't possibly be a lack of understanding on their part and therefore ranted about it as if they came from a place of understanding

Which is also a point

**Comment by Profpatsch** [comment] 2019-03-13 19:02
I think it’s valuable to include articles like these, because they provide good insight into the problems simple users tend to run into.

That the author discredits themselves by writing such a low-research blog post in the first place should be readily apparent to the observant reader. ;)

**Comment by matthiasbeyer** [comment] 2019-03-13 19:07
Did you actually read it?

Because it is rather low-quality and the author/s didn't seem to actually do their homework and research the stuff they're talking about. We have a discussion over in the IRC about that right now and we conclude that we do not have a problem with articles that have valid and constructive criticism in them, but this article does not so it shouldn't be in the newsletter.

**Comment by ddellacosta** [comment] 2019-03-13 19:20
Just wanted to state my full support for _not_ including pieces like this. Criticism is good, rants can even be fun and useful when they are coming from experience and have a seed of truth, but this piece is really low-quality. It reads as an incoherent, sputtering dump of generic complaints that are either simply wrong, incomplete, or could be said about any distribution or software project. Sometimes it's not even clear what the author is objecting to--go read the "Security" section for example, or the "Software Management" section which is simply a dump of a complex derivation with the comment, "Interesting, isn't it?" or ask yourself what the meaningful takeaway is from e.g. the "System Requirements" section...just for a few examples. Furthermore, it's filled with blatantly incorrect nonsense like

> Want to customize something in the OS, be ready, you’ll need to write your custom systemd service to do that.

(...from "Configuration Management")

Overall this piece is barely coherent, with no real actionable criticism. It's problematic to me that a newsletter published by the Nix community itself would include such a low-quality piece. Criticism is important, of course, but it should also be evaluated for inclusion based on its quality, not simply for possessing the quality of being critical.

**Comment by Profpatsch** [comment] 2019-03-13 19:22
> Did you actually read it?

yeah

**Comment by 7c6f434c** [comment] 2019-03-13 19:44
(Sorry, I would like to avoid going to IRC into a high-traffic discussion right now)

I did read the rant… On the net, I think it would be better if there are no links to rant like that in NixOS weekly.

I would like to say that:

1. In some political viewpoints low-quality criticism rising is good — to use Nix one has to learn, so anyone who has a good chance of benefitting from Nix will see that rant as a mess, and then they likely will intuitively associate criticisms of Nix approach with this rant. This viewpoint also feels a bit too dark…

2. On a slightly less dark note, there is some assertion of strength in linking to that, and the rant might be a kind of filter. I think people inside Nix project generally prefer understanding things, and at least put up with having to invest in learning to get that understanding — or just plain like learning concepts; empathising with the author of the rant _is_ a signal of high risk of not benefitting from Nix.

3. I think a strong argument _not_ to link the content with such a low quality is the following: NixOS weekly seems to be positively framed, so it is probably a bad idea to link to complaints of quality level that we sometimes prefer to ban than to cultivate.

**Comment by danbst** [comment] 2019-03-13 22:30
I don't get why this kind of articles should be censored. Negative feedback is a rare beast for NixOS, and I actually search for it. I also expect this to be a trend - someone invests into NixOS infra, then leaves company, then mgmt hires a new *DevOps* without realizing NixOS requires special kind of person, much more skilled and aware of functional languages, and pain experience starts. 

Maybe *you* don't want to know about this, but I'm on a crossroad - add Nix* things to current infra in current company, or make a strategic move **not to add**. Such articles help justify my decision.

If the problem is with sentiment analysis, then I'm on @oxij side in https://discourse.nixos.org/t/code-of-conduct-or-whatever/2134 - bullshit is often filtered unconsciously when I read smth. Sorry, I should have payed attention to actual *language* of that blog post. @matthiasbeyer is the *language* of the article what made you start this thead? I've read that article many times and I can't find what else (including kernel upgrade thing) is not constructive.

PS. Stop saying user is dumb and didn't research things. End goal for NixOS is to make life simpler for users, isn't it?

**Comment by domenkozar** [comment] 2019-03-14 02:59
The reason I let this one go through is:

a) It does contain some valid points, while some are unfounded. It's always easy to dismiss feedback based on some false information in it. It's harder to extract what is valid and address those and move on. I care about long-term outcome here.

b) I'm trying to be consistent with the culture of what we support/allow in Nix community. The post contains zero personal attacks (contrary to the fellas that Oxij tries to defend) and only attacks the tech itself.

c) The style it's written is not my favorite by far and you can see the author is frustrated. I do think that just makes the post more real as the feelings are well founded in this case. He feels helpless and reaches out for desperately to end the pain. Now, I think you can end up in such an emotional state with any technology nowadays if you take the wrong decisions so we still need to distill what went wrong.

All in all, I'd rather talk about what we can fix than what we can censor in this case, as [we're attacking the tone](https://en.wikipedia.org/wiki/File:Graham%27s_Hierarchy_of_Disagreement.svg) rather than the central point.

**Comment by ddellacosta** [comment] 2019-03-14 04:41
@domenkozar I apologize for jumping in aggressively while still being new to this community. I have yet to get a feel for how decisions are made and who is responsible, and I reacted without really thinking much about process. I'm going to dig my hole a bit deeper with this comment.

Let me reiterate that I am pretty new to Nix/NixOS. My impression so far, based on reading the documentation, is that the project is in dire need of an editor. I have more to say about this, but not here--I only mention it to emphasize that, to compound my experience with the documentation, seeing badly written articles promoted by the community itself is surprising and disappointing. It reinforces the impression I get that the community doesn't really care about good writing or how it is perceived by newcomers.

I dispute your characterization of the criticism of this piece as being exclusively about tone: my prior comment focused attention on multiple issues with the content (or lack thereof) of the piece, including highlighting factually incorrect information about NixOS, and those issues were just the low-hanging fruit. I do take issue with the tone, but that is because it reinforces my impression that the author was writing not in a thoughtful state of mind, but an agitated one.

In fact, I've written many pieces like this myself! I save them to a hidden directory somewhere to review again when I'm calm. They mostly never leave that directory.

I don't know if raising an issue is the appropriate way to begin a discussion of what something like "nixos-weekly" should be--I don't know anything about the administrative structure of this project or how included or rejected pieces are decided upon. If you _do_ want others' editorial opinions, then mine is: this is a poorly written piece that shouldn't be promoted by this community. And not because of its tone, but because this piece is the sort that would get a failing grade if it were submitted in a first-year essay writing class due to its poor structure and inability to make a persuasive argument, leaving aside anything else that could be said--such as the fact that *it contains information about NixOS that is wrong*.

And bad, wrong, emotionally-motivated criticism is damaging because it distracts from real, solvable problems (like docs which need better editing...). I'd love to hear more of what you or anyone else thinks this piece gets right, as I had difficulty finding anything.

I'll bow out of the conversation now. Certainly ignore me if you think I'm wrong, I'm just some guy who installed NixOS on his laptop a month or so ago and started hanging out in #nixos. But I like this project, and think it deserves a better baseline than this article.

**Comment by 7c6f434c** [comment] 2019-03-14 05:10
Re: personal attacks — I do have an impression that «these priorities you have are meaningless and useless and nobody reasonable should have such» was a non-trivial fraction of non-constructiveness in case of some of the bans, and does also happen in the rant in question.

Re: censoring/visibility — maybe we should also have a separate lists of all criticisms of Nix* that get noticed and pass some really low bar (like not naming any names and not containing a completely personal attacks?) with _no_ expectation of quality, or being up to the norms we try to cultivate re: vague attacks, not making easy mistakes?

I do agree that it is useful to have easy access to full range of criticism including criticism from people who obviously have priorities not compatible with using Nix* — and I also think it is useful to have thresholds there explicitly different from NixOS weekly.

(Of course having a list of positive references, maybe with a slightly higher standard of not saying untrue things and maybe not coming from a current committer — but nothing about explaining or substantiating the points — could be useful for symmetry or for people needing an emotional recharging)

**Comment by domenkozar** [comment] 2019-03-14 08:20
@ddellacosta thanks for your input - it's highly appreciated and welcomed. I'm open for discussion and I'm sure we can all agree there's no silver lining here.

I'll first address the dire need for an editor. I'm very well aware of how deep is the issue and in my [nixconf talk](https://www.youtube.com/watch?v=py26iM26Qg4&t=137s) I've laid out my plans to address two major issues that lack attention: documentation and infrastructure for teams. Further, there's [Seasons of Docs](https://discourse.nixos.org/t/season-of-docs-gsoc-for-documentation/2402/3) so if you know any technical editors it's time to help us out :)

>  It reinforces the impression I get that the community doesn't really care about good writing or how it is perceived by newcomers.

That is a correct observation, but it's not malicious. It's good to iterate that most of the contributors are not native English speaking, so we do need people like you to raise awareness, make a plan and execute it.

> I dispute your characterization of the criticism of this piece as being exclusively about tone: my prior comment focused attention on multiple issues with the content (or lack thereof) of the piece, including highlighting factually incorrect information about NixOS, and those issues were just the low-hanging fruit.

I take that back then, I didn't mean to say there was zero feedback on the content of the post, but that mostly it was addressing the tone. I do think it has some good claims with documentation and infrastructure/maturity for company use.

> I do take issue with the tone, but that is because it reinforces my impression that the author was writing not in a thoughtful state of mind, but an agitated one.

Here we do disagree. I do think that even for men, it's OK to express their feelings. Our culture has always been pushed to control feelings, but who says that's the best for everyone? In my view, it's fine to be angry with a tool and express that. Even with a human being, as long as you're respectful to others.

> I don't know anything about the administrative structure of this project or how included or rejected pieces are decided upon. 

I've been administrating/editing the weekly so I'd dare to say it's me with appreciated help with the community like you to help craft the content and the direction.

>  would get a failing grade if it were submitted in a first-year essay writing class due to its poor structure and inability to make a persuasive argument

I've addressed this before, as someone not speaking English natively I can assure you that English standards differ a lot country by country.

> leaving aside anything else that could be said--such as the fact that it contains information about NixOS that is wrong.

That is the part we agree on, I was skeptical mainly because the post itself does contain false information, maybe someone should contact the author and correct those mistakes if he's willing to?

>  I'd love to hear more of what you or anyone else thinks this piece gets right, as I had difficulty finding anything.

- small community -> for me personally that's a plus, but it can be tight for companies to hire and for support. Spot on.
- documentation -> while it's exaggerating and expressing feelings about it, that's a valid complaint to me
- only Nix -> this is true, Nix doesn't mix&match, so initial investment is big
- non-existent windows support -> hard to deny this one

I'll take a stoic approach here and say: we can't change the past, but we can improve the future. Would it help in the future to contact the author to correct factual information before publishing on weekly, but giving a pass on the tone?

**Comment by ddellacosta** [comment] 2019-03-14 16:30
@domenkozar I know I said I'd bow out, but I do want to respond to a few of your points, because I think I may have encouraged some misunderstandings in how I phrased things in my last response.

But before that, let me say: thank you for your thoughtful response!

> I've addressed this before, as someone not speaking English natively I can assure you that English standards differ a lot country by country.

My criticisms are not about the quality of any non-native's English! I lived outside of the United States in a non-English-speaking country for years, I have many friends and acquaintances for whom English is not their first language, and my wife is a non-native English speaker. I myself have experience writing in a language that is not my native language, in both a professional and social context, and I am very impressed with anyone who writes blog posts or documentation in a non-native language. It was obvious to me right away that this community is populated by a lot of non-native speakers of English. That's an incredibly positive thing, in my opinion. I am not out to alienate anyone or make anyone feel bad for doing something which I have a lot of respect for (and experience with myself).

So, I am very aware of the challenges non-native speakers face, and because of that, I try very hard to focus my criticisms on concerns related to the logical structure and factual content of a piece--not grammatical or spelling mistakes, unless they are so egregious that they are distracting, or if the author specifically requests that kind of feedback.

When I was talking about this piece's lack of coherence and persuasiveness in the context of a essay-writing class, that was not about the author's English skill, but their ability (as shown by this piece at least, the author may be very good in other contexts or with some editing) to convincingly put forth an argument supported by facts. I'd much rather read a piece by a non-native English speaker who is a logical and organized thinker than one written by a native speaker who can't string an argument together to save their life.

Take the Nix Pills for example--to a native speaker it has a number of grammatical errors, non-idiomatic expressions, and similar qualities that stick out. Certainly more than the piece we're discussing! But none of that matters much, because it's organized coherently, it follows a logical path from simple to complex concepts, and it illustrates all of its points with meaningful and comprehensible examples. Where I take issue with it is in a few places where I think the examples are unclear, or when it jumps ahead in a way I find confusing. Sure, I think it would benefit from fixing some of the minor errors that seem to arise from the fact that the author is a non-native speaker, but as-is I find it to be the best piece of documentation I've read yet (which includes the NixOS and nixpkgs manuals, and much of the wiki) for Nix.

I hope this makes it clear that I don't believe in criticizing someone for their English language skills, but I do hope to encourage _good writing_ in the form of clear arguments, logical thinking, good examples, factual content, and useful criticism.

> Here we do disagree. I do think that even for men, it's OK to express their feelings.

I don't disagree and I didn't mean to suggest otherwise. What I object to is that this piece is dominated by the anger and frustration of the author, to the degree that it seems to have clouded their judgment and prevented them from writing a quality piece. I don't think this is the same as suggesting we should not discuss our emotional reactions to things--just that I believe writing is better when you can talk about your emotional state with clarity and detachment. That's one of the values in writing: you can go back and change it before it's published.

> I'll take a stoic approach here and say: we can't change the past, but we can improve the future. Would it help in the future to contact the author to correct factual information before publishing on weekly, but giving a pass on the tone?

Before I respond to this--thank you for highlighting some of the criticism you found valuable, by the way. I don't necessarily agree with all of those points (I don't think it's worth mentioning a lack of Windows support, for example, considering the framing of the piece and what Nix is), and I think the overall quality of the piece along with the inclusion of incorrect information makes the entire thing suspect--but I won't belabor the point any further.

Looking toward the future: first of all, I'd be happy to help more if I can. I'll review your talk and the Seasons of Docs link and see if I can contribute further--thanks for sharing those!

As far as the right approach for addressing incorrect information in articles, I think what you proposed is a really good start--it seems like contacting an author before promoting their work could yield both better quality pieces and a better dialogue with the Nix community and those outside of it. I'll add that @7c6f434c raised some points that I agree with about the basic threshold for quality and fact-checking for including pieces, and I think it's worth nailing those down in a more formal fashion if possible.

Thank you for being so receptive to this discussion. It reinforces my impression of an engaged, generous, and serious community, however small. I'll try to contribute however I can.

**Comment by 7c6f434c** [comment] 2019-03-14 20:16
By the way, another point in favour of contacting authors: @ddellacosta writes «their ability (as shown by this piece at least, the author may be very good in other contexts or with some editing) to convincingly put forth an argument» where I would phrase is even more carefully — «their annoyance leading them to refuse spending energy on putting forth a convincing argument». But reaction of many people might indeed be closer to the former than to the latter. Advertising such a rant too much may be considered unkind to author — in the sense of making some of us evaluate the author starting from an instance of venting, not really of writing. (Again, what is done is done; and even through angry rant I _think_ some values and priorities are clear — and adversarial to values I want in software; hopefully this rant will not create problems between people for whom it was a good idea to work together).

**Comment by AndersonTorres** [comment] 2019-03-16 13:46
Being verily harsh: this article is just disgusting (I would use a curse word here, but let's try be polite).

Some valid criticism (confusing documentation, mainly) in a badly written rant.

> If you’re coming from OOP world it will be very difficult to understand that “language”

Hell, is this a valid criticism? It is like some C hacker complaining against FORTRAN matrix libraries...

> Forget about Chef, Puppet or Ansible! Only Nix expressions! Only hardcore!

Yes, that is the whole idea of NixOS! Using Nix as the only language to configure all the system, and not a bunch of unrelated config files with radically distinct syntax and semantics among them. "One lang to rule them all". Is it is so hard to understand?

> It requires a lot of CPU power to build it’s stuff and really a lot of space to store its multiple versions. 

Like, uh, Gentoo? And we can always collect the garbage...

**Comment by matthiasbeyer** [comment] 2019-03-19 19:02
.. And here is how it should be: https://www.reddit.com/r/archlinux/comments/b2jkrp/anyone_tried_nixos_what_are_your_thoughts/

Most of the feedback there is nice and constructive or at least can be helpful for us.

**Comment by domenkozar** [comment] 2019-03-20 10:13
@ddellacosta sorry for late answer. 

> I hope this makes it clear that I don't believe in criticizing someone for their English language skills, but I do hope to encourage good writing in the form of clear arguments, logical thinking, good examples, factual content, and useful criticism.

We're on the same page now :) I do agree that the article lacks a good technical discussion.  

> just that I believe writing is better when you can talk about your emotional state with clarity and detachment. That's one of the values in writing: you can go back and change it before it's published.

+1 again. I do wish that was the case in this article, but it got me thinking, if someone was willing to post such a piece, they must have really been frustrated. That's the part I do count as valid.

@7c6f434c 

> Advertising such a rant too much may be considered unkind to author 

That's not how internet works, each blog post should be written as it can hit the top of hacker news. That's the main premise why such news sites work in the first place :)

However, they have the option to remove the post if they wish so.

@AndersonTorres I do think it's valid to say that the mental model is very different from OOP. Maybe we should state that as a feature and be explicit about it? Same goes for the fact that Nix is a all or nothing. Same goes for docker. All those points are valid, but they are never mentioned anywhere.

I'm going to close this issue now, I think we went through the pros and cons. I'll make sure to have higher standards when publishing blog posts, or at the very least give authors valid feedback in case they could be improved.

**Closed as completed by domenkozar** 2019-03-20 10:13 UTC
